using System;
using System.Collections.Generic;
using System.Text;

namespace BuilderHacker.Abstraction.Attributes
{
    /// <summary>
    /// Attribute that marks a class to have a builder class generated by the BuilderGenerator.
    /// When applied to a class, the generator creates a nested builder class with fluent API support.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public class GenerateBuilderHackerAttribute : Attribute
    {
    }
}
